export const KEY_ODIN   = "odin-v6";
export const KEY_FLIP7  = "flip7-v2";
export const KEY_SKYJO  = "skyjo-v1";
export const KEY_RDN    = "rdn-v1";
export const KEY_QWIRKLE = "qwirkle-v1";
export const KEY_TM     = "tm-v1";
export const KEY_GROUPS = "scorekeeper-groups-v1";
export const COLORS  = ["#ff6e6c","#67d5b5","#f7c59f","#c3aed6","#5eb8ff","#ffd166"];
export const MEDALS  = ["\u{1F947}","\u{1F948}","\u{1F949}","4e","5e","6e"];
export const genId   = () => Date.now().toString(36) + Math.random().toString(36).slice(2,6);

export const GAMES = {
  odin: {
    key: KEY_ODIN,
    label: "Odin",
    emoji: "\u{1F426}‍⬛",
    color: "#c9933a",
    colorDim: "rgba(201,147,58,.12)",
    border: "#3a342c",
    surface: "#1d1a16",
    surface2: "#272320",
    bg: "#12100e",
    text: "#f5ead8",
    sub: "#8a7d6a",
    accent: "#f0c060",
    btnBg: "#c9933a",
    btnColor: "#12100e",
    desc: "Le moins de points gagne\nÉvitez d'atteindre la limite",
    defaultLimit: 15,
    limitLabel: "Éliminé à partir de",
    limitMin: 5, limitMax: 50, limitStep: 1,
    goalKey: "limit",
    winMode: "lowest",
  },
  flip7: {
    key: KEY_FLIP7,
    label: "Flip 7",
    emoji: "\u{1F0CF}",
    color: "#1f6feb",
    colorDim: "rgba(99,179,237,.12)",
    border: "#21262d",
    surface: "#161b22",
    surface2: "#21262d",
    bg: "#0d1117",
    text: "#e8f4fd",
    sub: "#8b949e",
    accent: "#63b3ed",
    btnBg: "#1f6feb",
    btnColor: "#fff",
    desc: "Le plus de points gagne\nPremier à atteindre l'objectif",
    defaultLimit: 200,
    limitLabel: "Objectif de points",
    limitMin: 50, limitMax: 500, limitStep: 50,
    goalKey: "goal",
    winMode: "highest",
  },
  skyjo: {
    key: KEY_SKYJO,
    label: "Skyjo",
    emoji: "♠️",
    color: "#7c3aed",
    colorDim: "rgba(124,58,237,.12)",
    border: "#2d1f4a",
    surface: "#1a1030",
    surface2: "#221540",
    bg: "#110c22",
    text: "#ede9f8",
    sub: "#8b7eaa",
    accent: "#c084fc",
    btnBg: "#7c3aed",
    btnColor: "#fff",
    desc: "Le moins de points gagne\nFin quand un joueur atteint 100 pts",
    defaultLimit: 100,
    limitLabel: "Fin de partie à",
    limitMin: 50, limitMax: 200, limitStep: 10,
    goalKey: "limit",
    winMode: "lowest",
    hasDouble: true,
  },
  rdn: {
    key: KEY_RDN,
    label: "Roi des Nains",
    emoji: "\u{1F451}",
    color: "#16a34a",
    colorDim: "rgba(22,163,74,.12)",
    border: "#1a3020",
    surface: "#0f1f14",
    surface2: "#162a1b",
    bg: "#091410",
    text: "#e8f5ec",
    sub: "#5a9a6a",
    accent: "#4ade80",
    btnBg: "#16a34a",
    btnColor: "#091410",
    desc: "Le moins de points gagne\nÉliminé quand la limite est atteinte",
    defaultLimit: 40,
    limitLabel: "Éliminé à partir de",
    limitMin: 10, limitMax: 100, limitStep: 5,
    goalKey: "limit",
    winMode: "lowest",
  },
  qwirkle: {
    key: KEY_QWIRKLE,
    label: "Qwirkle",
    emoji: "\u{1F9E9}",
    color: "#e85d04",
    colorDim: "rgba(232,93,4,.12)",
    border: "#3d1f0a",
    surface: "#231208",
    surface2: "#2e180c",
    bg: "#160b04",
    text: "#fdf0e8",
    sub: "#9a6a4a",
    accent: "#fb923c",
    btnBg: "#e85d04",
    btnColor: "#fff",
    desc: "Le plus de points gagne\nFormez des lignes de tuiles",
    defaultLimit: 100,
    limitLabel: "Objectif de points",
    limitMin: 50, limitMax: 300, limitStep: 10,
    goalKey: "goal",
    winMode: "highest",
    endOnDemand: true,
  },
  terraforming: {
    key: KEY_TM,
    label: "Terraforming Mars",
    emoji: "\u{1FA90}",
    color: "#b5451b",
    colorDim: "rgba(181,69,27,.14)",
    border: "#3d2010",
    surface: "#1e1208",
    surface2: "#2a1a0e",
    bg: "#120c05",
    text: "#f5e4d0",
    sub: "#8a6040",
    accent: "#f5a623",
    btnBg: "#b5451b",
    btnColor: "#f5e4d0",
    desc: "Le plus de points gagne\nScoresheet en fin de partie",
    defaultLimit: 999,
    limitLabel: "Limite",
    limitMin: 100, limitMax: 999, limitStep: 1,
    goalKey: "limit",
    winMode: "highest",
    endOnDemand: true,
    scoreType: "sheet",
    scoreFields: [
      { key: "tr",         label: "NT",          emoji: "🌡️", default: 20 },
      { key: "milestones", label: "Récompense",   emoji: "🏆", default: 0 },
      { key: "awards",     label: "Objectif",     emoji: "🎯", default: 0 },
      { key: "greeneries", label: "Forêts",       emoji: "🌲", default: 0 },
      { key: "cities",     label: "Villes",       emoji: "🏙️", default: 0 },
      { key: "cards",      label: "Cartes",       emoji: "🃏", default: 0 },
    ],
    extensions: [
      { key: "venusNext", label: "Venus Next", scoreField: { key: "venus",    label: "Vénus",    emoji: "♀️" } },
      { key: "colonies",  label: "Colonies",   scoreField: { key: "colonies", label: "Colonies", emoji: "🚀" } },
      { key: "prelude",   label: "Prelude",    scoreField: null },
      { key: "turmoil",   label: "Turmoil",    scoreField: null },
    ],
  },
};

export const DEFAULT_LIMITS = { odin: 15, flip7: 200, skyjo: 100, rdn: 40, qwirkle: 100, terraforming: 999 };
